apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-tooling

labels:
  - pairs:
      env: prod-tooling

resources:
  - namespace.yaml
  - ../../bases

patches:
  - path: deployment.yaml