apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooling-deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'tooling-role'
        vault.hashicorp.com/agent-inject-secret-database-cred.txt: 'app/data/database/config/dev'
    spec:
      serviceAccountName: tooling-sa

        # vault.hashicorp.com/agent-cache-enable: 'true'
        # vault.hashicorp.com/agent-inject-status: 'update'
        # vault.hashicorp.com/agent-inject-template-database-cred.txt: |
        #   {{- with secret "app/data/database/config/dev" -}}
        #   export db-username={{ .Data.data.username }}
        #   export db-password={{ .Data.data.password }}
        #   export db-host={{ .Data.data.password }}
        #   {{- end -}}