apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-tooling

labels:
  - pairs:
      env: dev-tooling

resources:
  - ../../bases
  - namespace.yaml
  - service-account.yaml
  # - pod.yaml



patches:
  - path: deployment.yaml